export const navItems = [
  { key: "home", index: "01", title: "活动首页", subtitle: "活动总览与历期入口", href: "index.html" },
  { key: "phase-1", index: "02", title: "第一期", subtitle: "第一期 | 南塘", href: "phase-1.html" },
  { key: "phase-2", index: "03", title: "第二期", subtitle: "第二期 | 人物志", href: "phase-2.html" },
  { key: "phase-3", index: "04", title: "第三期", subtitle: "第三期 | 寻找", href: "phase-3.html" },
  { key: "story", index: "05", title: "iMeeting共创故事", subtitle: "第三期共识生成记录", href: "story.html" },
  { key: "gratitude", index: "06", title: "合作丰碑", subtitle: "合作与贡献的纪念碑", href: "gratitude-design.html" },
  { key: "nt-flow", index: "07", title: "NT 流通", subtitle: "南塘豆流通数据递进", href: "nt-flow-progression.html" },
];

export const pages = {
  home: {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "首页导览",
    topbarIdentity: "活动首页",
    pageNumber: "01",
    banner: {
      kicker: "艺文共创 / 展览导览",
      handline: "从一次创作，到持续发生",
      title: "艺术\n共创营",
      intro: "不是一次传统的艺术课，也不是一次标准的乡村旅行——这是一场关于创作、协作与共同生活的开放式实验。从第一期的探索，到第二期的深耕，再到第三期的城市快闪展，这件事正在持续发生。",
      status: "第三期 · 城市快闪展",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ORIGIN",
        title: "缘起",
        paragraphs: [
          "一位来自北京的画师，为了寻找绘画灵感来到南塘。原本只是一次向乡村取景、向生活取材的停留，却在日复一日的田园生活里，看见了更多可能。",
          "蓦然回首，他发现灵感并不只在远方，也在院落、田埂、饭桌、闲谈和人与人的相处之间。于是，一个念头慢慢成形：能不能以自己的绘画专业为底色，邀请在地青年和远道而来的青年，一起在南塘生活、创作、相互看见？",
          "艺术共创营因此诞生。它发生在南塘合作社，也发生在南塘这片乡村生活之中。我们邀请大家来到这里，共同进行艺术共创，体会生活中的美，也体会群体合作中的美。",
        ],
        note: "从一个人的灵感寻找，走向一群人的共同创作。",
      },
      {
        type: "archive",
        eyebrow: "ARCHIVE",
        title: "历期共创营",
        intro: "从2025年11月至今，共创营已走完三期。每期主题不同——南塘、南塘人物志、寻找——但都是从这片土地和这群人里长出来的。",
        after: {
          eyebrow: "NEXT",
          text: "第四期正在筹备中，预计2026年暑假前后启动",
        },
        items: [
          {
            href: "phase-3.html",
            index: "03",
            tag: "第三期",
            line: "主题：寻找",
            image: "assets/images/archive-phase-3.png",
            title: "寻找自己，寻找自然，寻找关系",
            body: "2026年6月，26人参与，主题“寻找”。营期结束后参与者不愿离去，共同催生了城市快闪展。",
            reverse: false,
          },
          {
            href: "phase-2.html",
            index: "02",
            tag: "第二期",
            line: "主题：南塘人物志",
            image: "assets/images/archive-phase-2.jpg",
            title: "在观看之间，延展彼此的回应",
            body: "2026年1-2月，“南塘人物志”，采访村民故事创作工笔画，线上线下画展，20位共创人与20位村民访谈。",
            reverse: true,
          },
          {
            href: "phase-1.html",
            index: "01",
            tag: "第一期",
            line: "主题：南塘",
            image: "assets/images/archive-phase-1.jpg",
            title: "以场地为纸，写下第一笔共创",
            body: "2025年11月，22位共创人，集体确定“南塘”主题，探路成功。",
            reverse: false,
          },
        ],
      },
      {
        type: "credits",
        eyebrow: "ORGANIZING",
        title: "组办",
        people: [
          { name: "砚仁", role: "发起 / 组办", image: "assets/images/staff/砚仁.png" },
          { name: "䂫", role: "组办", image: "assets/images/staff/䂫.jpg" },
          { name: "若曦", role: "组办", image: "assets/images/staff/若曦.jpg" },
          { name: "朝林", role: "组办", image: "assets/images/staff/朝林.png" },
          { name: "富章", role: "组办", image: "assets/images/staff/富章.jpg" },
        ],
      },
      {
        type: "side-project",
        eyebrow: "SIDE PROJECT / CO-CREATE",
        title: "共创与支持",
        intro: "这部分仍在持续更新中，先记录目前参与支持页面与项目呈现的单位、伙伴和外部协作者。",
        statusLabel: "持续更新中",
        lanes: [
          {
            label: "Co-Create",
            groups: [
              {
                label: "外部协作者",
                items: ["南塘DAO", "南塘合作社", "南塘素社", "禧九诚食", "童彩梦·美述馆", "淅淅", "木木曦", "跳跳", "淑惠", "小白", "张超", "文峰", "明皓"],
              },
            ],
            chips: [],
          },
        ],
        contract: {
          before: "本页面是一个 AI Side Project，它是通过",
          linkLabel: "“共同契约”",
          after: "由淑慧、跳跳支持产出的，是一个MVP，如有错误、欠妥、考虑不周之处，请提供宝贵的可执行修改方法给 富章。",
          href: "https://imeeting.club/C03-coart-create-promotion/",
        },
      },
    ],
  },
  "phase-1": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第一期 · 南塘",
    pageNumber: "02",
    banner: {
      kicker: "ISSUE 01 / FIELD NOTE",
      handline: "以场地为纸，写下第一笔",
      title: "现场回声",
      intro: "2025年11月15日至30日（15天），主题由集体会议共同商定——“传承工笔，共创南塘”。22位共创人从全国各地而来，用画笔回应这片土地的风物与日常。从零开始，探路。",
      status: "2025年11月 · 第一期完成",
      noteTitle: "探路",
      noteText: "一群人一起画画到底行不行？结果出乎意料地好。大家画得开心，很多人说下次还要来。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY NOTE",
        title: "第一期 · 探路",
        paragraphs: [
          "第一期更像一次起笔。22位共创人从全国各地而来。不是一次传统的艺术课，也不是一次标准的乡村旅行，而是一场关于生活、创造与共同创作的开放式实验。",
          "那一期没有预设主题——是通过集体会议，大家一起定的“传承工笔，共创南塘”这个大方向，再分组确定小主题。也算探路，看看一群人一起画画到底行不行。",
          "结果出乎意料地好。大家画得投入，作品比想象中完整。结束时在南塘宿舍举办了结营画展，很多人说：下次还要来。",
        ],
        note: "第一期验证了最基础的问题：共创这件事，在南塘是可以成立的。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "22位共创人围绕“南塘”主题，以工笔画、水彩、拼贴等媒介回应了这片土地的日常与记忆。从蝶变到种子的希望，从南塘十二时辰到南塘意象，各组以独特的视角呈现了南塘的多重面貌。",
        items: [
          {
            reverse: false,
            meta: "CC",
            sideTitle: "破茧新生",
            sideLine: "蝶变",
            body: "画面是一双劳动人民的手，捧起一只破茧的蝴蝶，绿色的蝴蝶意味着新生和希望，也代表着南塘和新科技新技术结合所带来的新生和乡村未来的无限的可能和希望。",
            image: "assets/images/phase1/01_CC_破茧新生.jpg",
          },
          {
            reverse: true,
            meta: "狗狗猫",
            sideTitle: "如意",
            sideLine: "种子的希望",
            body: "习惯了以“人”为主的第一视角，但在种子的世界里，人类才最渺小。在土地里闷了上百天的种子大人们，一朝破土，带着巨大的能量与希望进入了人类的世界。种子不语，人类才是它们的孩子。",
            image: "assets/images/phase1/01_狗狗猫_如意.jpg",
          },
          {
            reverse: false,
            meta: "希言",
            sideTitle: "周一闲",
            sideLine: "南塘十二时辰",
            body: "“艺术的真谛需要自己去领悟”",
            image: "assets/images/phase1/01_希言_周一闲.jpg",
          },
          {
            reverse: true,
            meta: "徐佳彬",
            sideTitle: "百鬼夜行",
            sideLine: "南塘十二时辰",
            body: "“艺术的真谛需要自己去领悟”",
            image: "assets/images/phase1/01_徐佳彬_百鬼夜行.jpg",
          },
          {
            reverse: false,
            meta: "悠拉",
            sideTitle: "少女与猫",
            sideLine: "南塘意象",
            body: "我的创作灵感来自月月和她的朋友在素社爬树的场景。少女的天真活力无拘无束象征南塘有着无尽的可能性。素社还收养了流浪猫，给小动物一个温暖的家。",
            image: "assets/images/phase1/01_悠拉_少女与猫.jpg",
          },
          {
            reverse: true,
            meta: "KIKO",
            sideTitle: "南塘新生",
            sideLine: "蝶变",
            body: "从村里的第一个“小区”，到生态生姜，以及与茅台酒厂合作的生态小麦粮仓，再到此次艺术共创营二十余位参与者的在地实践。",
            image: "assets/images/phase1/01_KIKO_南塘新生.jpg",
          },
          {
            reverse: false,
            meta: "林曦",
            sideTitle: "芜湖·开饭",
            sideLine: "蝶变",
            body: "味味小猫被FC收编，有了新名字：“口哨呦吼”，为了让不会吹口哨的伙伴们知道叫什么，就有了“芜湖”。从无主人流浪猫到有家的芜湖。",
            image: "assets/images/phase1/01_林曦_芜湖-开饭.jpg",
          },
          {
            reverse: true,
            meta: "林曦",
            sideTitle: "芜湖·陪伴",
            sideLine: "蝶变",
            body: "味味小猫被FC收编，有了新名字：“口哨呦吼”，为了让不会吹口哨的伙伴们知道叫什么，就有了“芜湖”。从无主人流浪猫到有家的芜湖。",
            image: "assets/images/phase1/01_林曦_芜湖-陪伴.jpg",
          },
          {
            reverse: false,
            meta: "刘宇婷",
            sideTitle: "南塘里的徽派",
            sideLine: "南塘意象",
            body: "作者勾勒了皖美的徽派建筑，体验了南塘的历史文化，以笔墨书写了美好南塘。",
            image: "assets/images/phase1/01_刘宇婷_南塘里的徽派.jpg",
          },
          {
            reverse: true,
            meta: "小七",
            sideTitle: "更替",
            sideLine: "南塘十二时辰",
            body: "南塘的一天，从喜鹊啼鸣的清晨，到野火燃烧的午夜。乡村昼夜更替，时序轮转。",
            image: "assets/images/phase1/01_小七_更替.jpg",
          },
          {
            reverse: false,
            meta: "吕大侠",
            sideTitle: "月月",
            sideLine: "南塘十二时辰：子时",
            body: "南塘子时夜，水汽裹着花香，漫过村头藤架，月月蹲在青蔓间，荆条编的金冠坠着夜露。她轻拢掌心，蓝叶与夜色相融，定格了南塘子时独有的温柔，探进十二时辰最静谧的一刻。",
            image: "assets/images/phase1/01_吕大侠_月月.jpg",
          },
          {
            reverse: true,
            meta: "娜娜米",
            sideTitle: "有钱",
            sideLine: "种子的希望",
            body: "习惯了以“人”为主的第一视角，但在种子的世界里，人类才最渺小。在土地里闷了上百天的种子大人们，一朝破土，带着巨大的能量与希望进入了人类的世界。种子不语，人类才是它们的孩子。",
            image: "assets/images/phase1/01_娜娜米_有钱.jpg",
          },
          {
            reverse: false,
            meta: "陈宁雯",
            sideTitle: "篮中丰景",
            sideLine: "南塘意象",
            body: "这幅画用一个篮子装下了南塘的特色：生态花生、生姜、乡间植物，还有代表村子风貌的徽派建筑。它不仅展示了南塘的好物好风景，也象征合作的缩影。",
            image: "assets/images/phase1/01_陈宁雯_篮中丰景.jpg",
          },
          {
            reverse: true,
            meta: "晴子",
            sideTitle: "报喜",
            sideLine: "南塘十二时辰",
            body: "这幅作品以“南塘十二时辰”为灵感，撷取驻地创作的温暖记忆：出门就能见到的在田里蹦跶的喜鹊，合作社和素社往返路上撞见的黄澄澄的银杏，采风时瞅见的趣致的带有“囍”字窗的老屋。",
            image: "assets/images/phase1/01_晴子_报喜.jpg",
          },
          {
            reverse: false,
            meta: "世佳",
            sideTitle: "戴胜立于桑",
            sideLine: "南塘意象",
            body: "戴胜鸟立于桑枝，与南塘畔沉淀的皖北乡土之魂，共同晕染成一幅动静相生的田园诗画。",
            image: "assets/images/phase1/01_世佳_戴胜立于桑.jpg",
          },
          {
            reverse: true,
            meta: "谢树真",
            sideTitle: "麻雀的早餐桌",
            sideLine: "南塘十二时辰：辰时",
            body: "快看！南塘村的麦苗餐厅开张啦！绿色的麦苗又软又滑，露珠为它挂上了亮晶晶的小灯泡。一位身穿棕色外套的麻雀小客人，正轻轻踩在湿漉漉的泥土上，歪着小脑袋研究着。",
            image: "assets/images/phase1/01_谢树真_麻雀的早餐桌.jpg",
          },
          {
            reverse: false,
            meta: "田田",
            sideTitle: "大地书房",
            sideLine: "蝶变",
            body: "场景为合作社的大地书房，画中心是猫咪双双和对对，大地书房是本次工笔画共创营的核心地点。",
            image: "assets/images/phase1/01_田田_大地书房.jpg",
          },
          {
            reverse: true,
            meta: "亭真",
            sideTitle: "萝卜白菜",
            sideLine: "南塘意象",
            body: "“萝卜白菜规则”是罗伯特议事规则落地南塘时生长出的民间智慧。规则本身并不复杂，却需求每个人向前一步，共同努力。",
            image: "assets/images/phase1/01_亭真_萝卜白菜.jpg",
          },
          {
            reverse: false,
            meta: "桶桶",
            sideTitle: "福来",
            sideLine: "种子的希望",
            body: "习惯了以“人”为主的第一视角，但在种子的世界里，人类才最渺小。在土地里闷了上百天的种子大人们，一朝破土，带着巨大的能量与希望进入了人类的世界。种子不语，人类才是它们的孩子。",
            image: "assets/images/phase1/01_桶桶_福来.jpg",
          },
          {
            reverse: true,
            meta: "蔡文瑜",
            sideTitle: "好运",
            sideLine: "种子的希望",
            body: "习惯了以“人”为主的第一视角，但在种子的世界里，人类才最渺小。在土地里闷了上百天的种子大人们，一朝破土，带着巨大的能量与希望进入了人类的世界。种子不语，人类才是它们的孩子。",
            image: "assets/images/phase1/01_蔡文瑜_好运.jpg",
          },
          {
            reverse: false,
            meta: "小也",
            sideTitle: "常乐",
            sideLine: "种子的希望",
            body: "习惯了以“人”为主的第一视角，但在种子的世界里，人类才最渺小。在土地里闷了上百天的种子大人们，一朝破土，带着巨大的能量与希望进入了人类的世界。种子不语，人类才是它们的孩子。",
            image: "assets/images/phase1/01_小也_常乐.jpg",
          },
          {
            reverse: true,
            meta: "淅淅",
            sideTitle: "金杏南塘",
            sideLine: "蝶变",
            body: "用一棵平凡的银杏树描绘出平淡而富有生机的南塘日常。为银杏点金，变银杏为“金杏”，代表着对富饶南塘的期盼与向往。",
            image: "assets/images/phase1/01_淅淅_金杏南塘.jpg",
          },
          {
            reverse: false,
            meta: "杨媛",
            sideTitle: "丰收年",
            sideLine: "南塘意象",
            body: "一家人在老树下的田垄里收着金黄的作物，风量着稻子的香，喜鹊一家在树枝上停留，每一缕阳光都裹着团圆的暖。",
            image: "assets/images/phase1/01_杨媛_丰收年.jpg",
          },
          {
            reverse: true,
            meta: "周周",
            sideTitle: "生长",
            sideLine: "蝶变",
            body: "取景自南塘素社，这棵树见证着小学变素社，孩童变青年。南塘就像这棵树，扎根于这片土地，伸出枝干向外链接，穿过河流，流淌进人们心中。星光代表无数人所贡献的力量。",
            image: "assets/images/phase1/01_周周_生长.jpg",
          }
        ],
      },
    ],
  },
  "phase-2": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第二期 · 南塘人物志",
    pageNumber: "03",
    banner: {
      kicker: "ISSUE 02 / RESPONSE NOTE",
      handline: "让回响慢慢成形",
      title: "现场回声",
      intro: "2026年1月15日至2月4日（22天），主题定为“南塘人物志”。20位共创人进入村庄，采访村民的故事，用工笔画人物回应南塘的真实面孔。线上线下同步展览。",
      status: "2026年1-2月 · 第二期完成",
      noteTitle: "验证",
      noteText: "第二期验证了一件事：即使收一点费用，这件事依然成立。作品更完整，默契也更深。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY NOTE",
        title: "第二期 · 人物志",
        paragraphs: [
          "第二期不再只是起步。不同的是——部分第一期共创人被正式邀请成为本期的工作人员。他们不再只是参与者，而是参与到组织、执行、协调与支持中的“共建者”。经验不是被消耗，而是被继承。",
          "主题定为“南塘人物志”，以工笔画学习与创作为主线，描绘独属于南塘的平民史诗。以NT实景游戏为支线，帮助共创人真实参与、理解和使用南塘的社区机制。依然来了20位共创人。当初说“下次还要来”的人，很多真的又来了。",
        ],
        note: "从探路到深耕，共创营在每一次迭代中慢慢找到自己的节奏。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "20位共创人围绕“南塘人物志”主题，以肖像和场景叙事呈现南塘真实的人物与故事——有合作社的阿姨、村口闲坐的老人、回乡创业的青年。分“看见·SeeHer”“五福润乡野”“时间之间”“循时而生”四个方向展开。",
        items: [
          {
            reverse: false,
            meta: "世佳",
            sideTitle: "时光之轮",
            sideLine: "时间之间",
            body: "我把时间画成一个圆，不为标记起点或终点，而是承认它从未停下。人行走在指针之上，只留下姿态与物品，作为工作与存在的痕迹。",
            image: "assets/images/phase2/02_世佳_时光之轮.jpg",
          },
          {
            reverse: true,
            meta: "小唯",
            sideTitle: "朝林",
            sideLine: "看见·SeeHer",
            body: "来自贵州的实习女孩“朝林”，如牵牛花（朝颜）般质朴坚韧，名字里的“朝”与朝颜呼应，“林”藏着山野生长的韧劲。",
            image: "assets/images/phase2/02_小唯_朝林.jpg",
          },
          {
            reverse: false,
            meta: "图图",
            sideTitle: "五福·富",
            sideLine: "五福润乡野",
            body: "南塘刘娟姐，在自家沙场身姿利落、神采爽朗，一腔干劲藏于眉眼，满心热忱付于日常。",
            image: "assets/images/phase2/02_图图_五福-富.jpg",
          },
          {
            reverse: true,
            meta: "水清浅",
            sideTitle: "五福·德",
            sideLine: "五福润乡野",
            body: "花店老板娘心秉攸好德，守着一方花肆，以善念侍花，以诚心待人。",
            image: "assets/images/phase2/02_水清浅_五福-德.jpg",
          },
          {
            reverse: false,
            meta: "菱形",
            sideTitle: "脊梁",
            sideLine: "看见·SeeHer",
            body: "以忍冬为魂，绘就一位89岁的南塘建设者刘贵莲。她拉石种麦的信仰与坚韧，如藤蔓般在新南塘的山水屋舍间绵延生长。",
            image: "assets/images/phase2/02_菱形_脊梁.jpg",
          },
          {
            reverse: true,
            meta: "大泡",
            sideTitle: "晨乡牧场",
            sideLine: "时间之间",
            body: "人生有坦途，创业有艰辛。每天一早乡村企业家张春，要照顾自家的羊和牛。凭着努力克服身残不便、指导代养农户一起带动乡亲致富！",
            image: "assets/images/phase2/02_大泡_晨乡牧场.jpg",
          },
          {
            reverse: false,
            meta: "阿山",
            sideTitle: "杨素芬·午后暖阳",
            sideLine: "看见·SeeHer",
            body: "那天雪后初晴，午后日光温柔，锅碗瓢盆停下交响，世界安静了，杨素芬终于可以放松下来，在厨房前坐下晒晒太阳。我喊了一声杨姨，她抬头冲我笑，比阳光还好看。",
            image: "assets/images/phase2/02_阿山_杨素芬-午后暖阳.jpg",
          },
          {
            reverse: true,
            meta: "䂫",
            sideTitle: "捧着苹果的姑娘",
            sideLine: "看见·SeeHer",
            body: "苹果感觉就是一种非常神奇的水果，它没有那么的美丽，也没有那么的普通。但是他有一种起始的感觉，正如同我们主题种子的意向开始和希望。",
            image: "assets/images/phase2/02_䂫_捧着苹果的姑娘.jpg",
          },
          {
            reverse: false,
            meta: "树",
            sideTitle: "簇拥",
            sideLine: "看见·SeeHer",
            body: "小女孩（杨默）恬静的面容，安然的靠在花丛中。初春般绽放的小黄花，簇拥着女孩长大，希望她烦恼少少，胃口好好。",
            image: "assets/images/phase2/02_树_簇拥.jpg",
          },
          {
            reverse: true,
            meta: "味味",
            sideTitle: "芬",
            sideLine: "看见·SeeHer",
            body: "绘张永芬着明制汉服侧影。发簪玉兰映其坚韧乐观，绒领衬柔，绿背景传生机。",
            image: "assets/images/phase2/02_味味_芬.jpg",
          },
          {
            reverse: false,
            meta: "阿炜",
            sideTitle: "万物生长",
            sideLine: "时间之间",
            body: "早餐店的老板有着很丰富的灵魂，院子里五颜六色的蔬果变成可口的早餐，为早上忙碌的人提供一天之始的能量。",
            image: "assets/images/phase2/02_阿炜_万物生长.jpg",
          },
          {
            reverse: true,
            meta: "橘子",
            sideTitle: "时间中间",
            sideLine: "时间之间",
            body: "总有不同的创作者来到南塘，他们也会围着篝火，在夜空下载歌载舞。创作者们是流动的，也是永恒的。",
            image: "assets/images/phase2/02_橘子_时间中间.jpg",
          },
          {
            reverse: false,
            meta: "廉er",
            sideTitle: "小时谭记",
            sideLine: "时间之间",
            body: "逢年过节，大家都来吃油糕啦。刚出锅的糕，胖乎乎、圆滚滚的空心脆皮糖糕…",
            image: "assets/images/phase2/02_廉er_小时谭记.jpg",
          },
          {
            reverse: true,
            meta: "墩墩",
            sideTitle: "杨素芬·正午烟火",
            sideLine: "时间之间",
            body: "十二点钟声里，是五八年生的杨素芬阿姨在素社灶台忙碌为大家做饭的时间。她以多年不变的奉献和坚守，守护着南塘的炊烟和这片土地。",
            image: "assets/images/phase2/02_墩墩_杨素芬-正午烟火.jpg",
          },
          {
            reverse: false,
            meta: "若曦",
            sideTitle: "果子·喜",
            sideLine: "循时而生",
            body: "画面中人物是草莓种植户邵海贝最小的孩子，这张画源于一个真实瞬间——他手里拿着自己刚从草莓地里摘的草莓想要分享给别人。",
            image: "assets/images/phase2/02_若曦_果子-喜.jpg",
          },
          {
            reverse: true,
            meta: "星晴",
            sideTitle: "有花开“莓”烦恼",
            sideLine: "循时而生",
            body: "小组以草莓的生长周期与老板的人生阶段相结合。草莓开花期象征着海贝姐的事业和生活好了起来，锦上添花。",
            image: "assets/images/phase2/02_星晴_有花开莓烦恼.jpg",
          },
          {
            reverse: false,
            meta: "徐缓",
            sideTitle: "结果之后",
            sideLine: "循时而生",
            body: "画面以“衰老与新生”为核心主题：腐烂的果实，枯萎的母株，生命走向撤退；而在其上方，一株新芽正缓慢生长。",
            image: "assets/images/phase2/02_徐缓_结果之后.jpg",
          },
          {
            reverse: true,
            meta: "kk",
            sideTitle: "植苗·生盼",
            sideLine: "循时而生",
            body: "这张是我们草莓园系列工笔画其一，锚定草莓种植开篇的植苗瞬间，以植苗这一耕耘起点为芯，将邵海贝的初心、对生长的期许与土地里孕育的希望相融。",
            image: "assets/images/phase2/02_kk_植苗-生盼.jpg",
          },
          {
            reverse: false,
            meta: "cc",
            sideTitle: "红颜",
            sideLine: "循时而生",
            body: "画中，海贝姐俯身采摘，指尖轻捻的红颜草莓如红宝石闪烁，垄间果实累累，映着她专注的侧脸。",
            image: "assets/images/phase2/02_cc_红颜.jpg",
          },
          {
            reverse: true,
            meta: "章先生",
            sideTitle: "五福·全村的希望",
            sideLine: "五福润乡野",
            body: "在南塘，不缺理想者、为民请命斗士和朴实的奋斗者。而孩子是人类的未来，科技是生产核心生产力。",
            image: "assets/images/phase2/02_章先生_五福-全村的希望.jpg",
          },
          {
            reverse: false,
            meta: "小孙",
            sideTitle: "五福·寿",
            sideLine: "五福润乡野",
            body: "以党姨煮粥场景入画，借烟火日常传递温暖和对长辈安康长寿的祝愿。",
            image: "assets/images/phase2/02_小孙_五福-寿.jpg",
          },
          {
            reverse: true,
            meta: "小夏",
            sideTitle: "五福·善",
            sideLine: "五福润乡野",
            body: "如果记忆有味道，对南塘素舍的记忆则是刘姨做的萝卜白菜小黄姜 三菜加一汤。",
            image: "assets/images/phase2/02_小夏_五福-善.jpg",
          }
        ],
      },
    ],
  },
  "phase-3": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第三期 · 寻找",
    pageNumber: "04",
    banner: {
      kicker: "ISSUE 03 / ONGOING FIELD",
      handline: "寻找",
      title: "现场回声",
      intro: "2026年6月6日至22日（17天），主题“寻找”。不是拍脑袋——是观察到这段时间大家都不太好过，很多人都在找方向、找自己、找一种不那么焦虑的活法。26人参与，10位核心共创人。",
      status: "2026年6月 · 第三期 · 城市快闪展",
      noteTitle: "自然生长",
      noteText: "这期营本来计划到6月21号结束。但大家不太想走——于是有了营期延长的动议，有了展览的筹划，城市快闪展就这样从共创营内部长了出来。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY DETAIL",
        title: "第三期 · 寻找",
        paragraphs: [
          "第三期的主题叫“寻找”。不是拍脑袋——是观察到这段时间大家的状态：就业不容易，未来不太确定，很多人都在找方向、找自己、找一种不那么焦虑的活法。",
          "十个共创人，在这个大主题下分成了三个方向：寻找自己，寻找自然，寻找关系——从仙人掌丛中的自语，到书页里的荷塘，再到柚子花香中的美梦，每张画布以不同的方式回应同一个问题。",
          "这期营本来计划6月21号结束。但大家不太想走，还想多留一段时间共同画画。于是有了动议，形成了方案，汇集了支持——城市快闪展就这样长了出来。",
        ],
        note: "感谢禧九诚食的潘掌柜、童彩美述馆的张静老师，还有在地的方哥。没有他们，这个展不会出现在这里。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "10位共创人围绕“寻找”主题，在三个方向上各自交出回应。",
        items: [
          {
            reverse: false,
            meta: "慢慢",
            sideTitle: "属于我的只有自己",
            sideLine: "荆棘丛中，守住本心",
            body: "置身茂密的仙人掌丛，周遭满是隔阂与疏离，独留一人在此徘徊探索，在独处中与内心对话。外界皆是荆棘，唯有守住本心，学会依靠自己，完成自我找寻。",
            image: "assets/images/phase3/manman.jpg",
          },
          {
            reverse: true,
            meta: "Gloria",
            sideTitle: "书中自成风景",
            sideLine: "方寸之间，寻见自然",
            body: "书页为塘，荷风自来。方寸之间，寻见自然。",
            image: "assets/images/phase3/gloria.jpg",
          },
          {
            reverse: false,
            meta: "西瓜",
            sideTitle: "真·假",
            sideLine: "假作真时真亦假",
            body: "假作真时真亦假，真作假时假亦真。",
            image: "assets/images/phase3/xigua.jpg",
          },
          {
            reverse: true,
            meta: "陨",
            sideTitle: "与柚眠",
            sideLine: "做一场睡在柚子里的美梦",
            body: "柚子花开了，请和小猫蛋黄一起做一个睡在柚子里的美梦吧～",
            image: "assets/images/phase3/yun.jpg",
          },
          {
            reverse: false,
            meta: "念儿",
            sideTitle: "共栖之境",
            sideLine: "允许所有情绪都有停留的位置",
            body: "作品以心脏作为内在自我的象征，以环绕其周围牵手而行的星星代表不同的情绪状态。冷暖交织的色彩并非对立，而是情绪共同存在的写照。画面通过内外两个空间构建出心灵与世界的关系：内在世界如梦境般温柔丰盈，外在世界充满未知与可能；表达一种对自我的接纳——允许所有抵达心中的情绪，都能拥有停留的位置。",
            image: "assets/images/phase3/nianer.jpg",
          },
          {
            reverse: true,
            meta: "宏心",
            sideTitle: "心花怒放",
            sideLine: "心如画师造万象",
            body: "妙手拈莲藏赤心，星河作境绘凡尘。心如画师造万象，方寸莲台容乾坤。素莲一点纳仓宇，柔指拈花证本真。吾身本是大千界，一念随心造古今。",
            image: "assets/images/phase3/hongxin.jpg",
          },
          {
            reverse: false,
            meta: "墨染辰光",
            sideTitle: "行走南塘",
            sideLine: "向内自省，向外观世",
            body: "以行禅、观心、绘画向内自省；以采风、务农、相伴向外观世，找寻本真自我。取《心经》“颠倒梦想，究竟涅槃”之意，借倒置画面自警：破虚妄，离执念，得自在。",
            image: "assets/images/phase3/moranchenguang.jpg",
          },
          {
            reverse: true,
            meta: "哲理不吃鱼",
            sideTitle: "赤色呼吸",
            sideLine: "聆听大地脉搏",
            body: "自然从不是一成不变的景致，寻找自然，实则是聆听大地脉搏。落日缓缓铺开霞光，轻轻笼罩山野天地。愿我们在感知里，静心观天地，与万物相融共生。",
            image: "assets/images/phase3/zhelibuchiyu.jpg",
          },
          {
            reverse: false,
            meta: "茵籽呀",
            sideTitle: "沃土新翼",
            sideLine: "田垄与墨痕在此相望",
            body: "麦穗沉实，凝着南塘世代深扎的乡土根脉；书卷轻启，新枝舒放，蓝鸟划破旧日寂静，衔来时代回响，映照求新求变的智识光芒。田垄与墨痕在此相望，底蕴与拓新悄然共生。",
            image: "assets/images/phase3/yinsi.jpg",
          },
          {
            reverse: true,
            meta: "晴子",
            sideTitle: "“鸭”比囧囧囧",
            sideLine: "奔赴认清自我的必经之路",
            body: "裹着花瓣斗篷的小鸭眉眼低落，困在柔软云团里迷茫彷徨。祥云环绕，温柔色彩包裹着懵懂不安，描绘自我找寻途中的低落时刻，即便满心囧态，也是奔赴认清自我的必经之路。",
            image: "assets/images/phase3/qingzi.jpg",
          },
        ],
      },
      {
        type: "cocreators",
        eyebrow: "CO-CREATORS",
        title: "共创人",
        intro: "第三期的十位共创人，各自以绘画语言回应了“寻找”这个主题。以下是部分共创人介绍。",
        items: [
          {
            reverse: false,
            label: "CO-CREATOR 01",
            name: "宏心",
            role: "SHE HAS A BIG HEART.",
            bio: "28岁自由职业，南艺毕业，以画入道，常驻寺院，深山隐居，修行智慧，写字画画，参禅打坐，认为灵魂是艺术的创作，艺术是灵魂的表达。北方人爱玩好相处。",
            image: "assets/images/cocreators/hongxin.jpeg"
          },
          {
            reverse: true,
            label: "CO-CREATOR 02",
            name: "Gloria🐬",
            role: "Journey never ends!",
            bio: "喜山乐水，钟情自然，独自游历四方旅途，这一站：阜阳南塘。期待在色彩与线条中，重新找回绘画的快乐。步履与创作，永无止境。",
            image: "assets/images/cocreators/gloria.jpeg"
          },
          {
            reverse: false,
            label: "CO-CREATOR 03",
            name: "西瓜🍉",
            role: "SWEET AS A WATERMELON",
            bio: "INFP，觉得自己是个无趣的普通人，间歇性努力，持续性摆烂。现在的愿望是提前退休。",
            image: "assets/images/cocreators/xigua.jpeg"
          },
          {
            reverse: true,
            label: "CO-CREATOR 04",
            name: "茵籽",
            role: "A CANTONESE WITH STANDARD MANDARIN",
            bio: "前金融国企搬砖人，开朗的i人，间歇性叛逆，随性爱探索。期待和大家结伴、学习、听风、寻趣、共行。",
            image: "assets/images/cocreators/yinsi.jpeg"
          },
          {
            reverse: false,
            label: "CO-CREATOR 05",
            name: "陈若雨",
            role: "LOVER OF NATURE",
            bio: "喜欢自然的学前教育大三学生。",
            image: "assets/images/cocreators/chenruoyu.jpeg"
          },
          {
            reverse: true,
            label: "CO-CREATOR 06",
            name: "慢慢",
            role: "SHE COMES FROM THE NORTHEAST",
            bio: "来自东北的小冻梨，负责给大家的东北话教学。早起养生的八段锦和夜晚后的微醺小酒都可以。以《属于我的只有自己》参展——在仙人掌丛中，画下守住本心的自语。",
            image: "assets/images/cocreators/manman.jpeg"
          },
          {
            reverse: false,
            label: "CO-CREATOR 07",
            name: "霜霜",
            role: "I/E PERSONALITY FLIPPER",
            bio: "本人i/E人格反复横跳，想法很多的射手座，正在探寻自己的更多可能性，对没接触过的事都蛮有兴趣的。",
            image: "assets/images/cocreators/shuangshuang.jpeg"
          },
          {
            reverse: true,
            label: "CO-CREATOR 08",
            name: "墨染辰光",
            role: "SHE LIKES NATURE",
            bio: "大家可以叫我辰光，来自湖北。期待这次旅程，和大家成为朋友，共创美好时光！以《行走南塘》参展——向内自省，向外观世，找寻本真自我。",
            image: "assets/images/cocreators/moranchenguang.jpeg"
          },
          {
            reverse: false,
            label: "CO-CREATOR 09",
            name: "晴子",
            role: "LOVE IS THE NEW WORLD",
            bio: "24岁，爱旅行，爱尝试，爱体验。以《鸭比囧囧囧》参展——即便满心囧态，也是奔赴认清自我的必经之路。",
            image: "assets/images/cocreators/qingzi.jpeg"
          },
          {
            reverse: true,
            label: "CO-CREATOR 10",
            name: "niya",
            role: "A VERY CUTE LITTLE GIRL",
            bio: "一位正在gap的自由设计师，还没想好未来要怎么走。在迷茫午后遇见了DAO，所以先来南塘和伙伴们相遇吧。",
            image: "assets/images/cocreators/niya.jpeg"
          },
        ],
      },
    ],
  },
  story: {
    width: 488,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "iMeeting共创故事",
    topbarIdentity: "第三期 · iMeeting共创故事",
    pageNumber: "05",
    banner: {
      kicker: "IMEETING CO-CREATION STORY",
      handline: "青年版可操作的民主",
      title: "iMeeting共创故事",
      intro: "这一页记录第三期共创营从筹备到城市快闪展的过程纪事。它的底色，是一场青年版的可操作民主：用现代工具保存表达，用共同规则凝聚共识，再把共识推进成可实践的合作。",
      status: "可实践的合作",
      noteTitle: "从表达，到共识",
      noteText: "第三期的许多决定，并不是预先写好的，而是在 iMeeting 中被提出、记录、修正和确认。萝卜规则让每个人依次表达，南塘十二条让讨论有章可循；于是会议不只是流程，而成为把个人声音凝聚为共识、把共识落到行动里的合作现场。",
    },
    sections: [
      

      {
        type: "timeline",
        eyebrow: "CHRONICLE",
        title: "第三期共创纪事",
        intro: "整个第三期的推进，本身就是「南塘十二条」议事规则的一次完整演练。沿着时间轴，看一群人是如何通过规则，把想法变成决议、把决议变成现实的。",
        items: [
          {
            date: "2026.04.16",
            phase: "2026.04.16 / 第一轮议题",
            title: "议题提出：第三期要不要做",
            body: "4月16日，第一次筹备会议。议题很原始：第三期还做不做？如果做，大概做成什么样？这是一次信息澄清会（事实）：回顾前两期的经验和资源，了解当前团队的状态和能力，梳理外部合作的意向。没有表决，但所有人在同一信息面上离开会场。\n\n结论：做。但具体怎么做，留到下一轮。",
          },
          {
            date: "2026.05.18",
            phase: "2026.05.18 / 议题收窄",
            title: "目标辩论：做什么，不做什么",
            body: "5月18日，第二次筹备会议。议题变为：第三期的目标是什么？\n\n进入观点表达阶段：有人主张延续第二期的人物志方向，有人提出换一个主题、尝试新的可能，有人关注收费模式是否可持续。不同观点被逐一记录和讨论。\n\n通过辩论，方向逐步收窄：不做第二期的延续，做一期新的主题。收费标准从「免费还是收费」的二元选择，收敛为「收多少、怎么收」的可操作问题。\n\n结论：做新主题、确定收费方向。具体主题和金额留到下一步。",
          },
          {
            date: "2026.05.21",
            phase: "2026.05.21 / 边界确认",
            title: "合作边界：与南塘合作社达成共识",
            body: "5月21日，与南塘合作社的两场连开会议。议题明确：共创营要借用合作社的场地和资源，合作条件是什么？\n\n这是典型的动议前准备工作（信息）：双方依次澄清各自的诉求和底线——合作社能提供什么空间、食宿标准、费用结构；共创营需要什么支持、能回馈什么。\n\n经过两轮沟通，边界条件被逐一确认：场地使用范围、食宿费用计算方式、劳动互助的协作机制。这些确认后的条件，成为后续一系列动议的事实基础。",
          },
          {
            date: "2026.06.05",
            phase: "2026.06.05 / 筹备会总动员",
            title: "第一项正式动议：主题「寻找」与599元",
            body: "6月5日，第三期筹备会总动员。在前期信息充分澄清的基础上，两项核心议题进入表决程序：\n\n第一项动议：第三期主题。经过此前多轮讨论的沉淀，「寻找」被正式提出并获得一致同意。\n\n第二项动议：收费标准和NT（南塘豆）预算框架。599元的收费方案被提出，NT发行总量上限定在约3.3万元。动议通过。\n\n同日确定了营期的基本日程框架：6月6日-22日，17天。",
          },
          {
            date: "2026.06.07",
            phase: "2026.06.07 / 规则学习",
            title: "议事规则分享：先学会怎么一起做决定",
            body: "6月7日，议事规则分享会。在进入正式的共创阶段之前，所有人先花一整天学习「南塘十二条」：动议怎么提、辩论怎么进行、表决怎么计数、修正案怎么处理。\n\n这不是一次知识灌输，而是一次工具交付。因为从这一刻起，每一件事都将由大家依规则共同决定。\n\n练习议题：共居公约。每个人提出自己认为必要的共居规则——作息时间、公共空间使用、劳动分工——这些不是由主办方规定的，而是通过动议→辩论→表决的流程，一条一条定下来的。",
          },
          {
            date: "2026.06.08",
            phase: "2026.06.08 / 第二次会议",
            title: "主动议：分组方案与创作主题的确定",
            body: "6月8日下午，第二次会议。议题：如何分组、每个人画什么。\n\n富章提出一项主动议——采用【自荐队长+主题前置+自主选组】模式：先由愿意担任队长的人陈述自己的创作方向，其他成员根据兴趣自主选择加入哪一组。如果某组人数超限，由队长反选。\n\n这项动议经历了完整的议事流程：提议人陈述理由（信息）→ 参会者提问澄清（理解）→ 支持方与反对方依次发言（观点）→ 表决通过。\n\n结果：当场形成了3个创作小组，各有明确的主题方向和负责人。分组不是分配，而是每个人在规则框架下的自主选择。",
          },
          {
            date: "2026.06.11",
            phase: "2026.06.11 / 第三次会议",
            title: "议题展开：展览落地的细节逐项澄清",
            body: "6月11日上午，第三次会议。分组和创作方向确定后，新议题浮现：展览怎么办？\n\n这是一次典型的细节澄清会议。没有动议，而是用大量提问来逼近可操作方案：\n\n• 展览场地选哪里？有人提议合作社，有人提议宿舍。经过讨论，合作社优先（村民熟悉、交通便利），宿舍作为备选方案。\n• 拍卖怎么搞？线上线下并行：线下现场拍卖、线上同步竞拍。允许场外认识的人参与。\n• 肖像费问题：画村民肖像是否需要支付肖像费？如果需要，比例怎么定？各方观点被记录，留待后续表决。\n\n信息公开和观点表达，是未来动议的前提。",
          },
          {
            date: "2026.06.12",
            phase: "2026.06.12 / 深入对话",
            title: "无议程的开放讨论：共创营的长期方向",
            body: "6月12日，一次没有预设议程的深度对话。议题不在眼前，而在远处：共创营到底要长成什么样？\n\n砚仁、富章、跳跳、和光同尘四人开放讨论了共创营的长期方向：盈利是否意味着市场买单，影响力能否转化为资金支持，团队的可复制性如何建立。\n\n没有表决，没有决议。但这次对话让在场的人对「我们为什么要做这件事」有了更清晰的共识。在议事规则的框架里，不是每一场会都要产出决议——有时候，让共识先于决议形成，才是更基础的一步。",
          },
          {
            date: "2026.06.13",
            phase: "2026.06.13 / 第四次会议",
            title: "创作推进与展览方案的细化",
            body: "6月13日，第四次会议（含2场续会）。创作已全面展开，新议题集中在展览筹备的具体事务上。\n\n会议围绕宣发方案、场地布置分工、预算调整等议题展开事实澄清和观点表达。NT系统的使用问题被重点讨论——如何让村民更方便地参与进来，数字工具的操作门槛怎么降低。\n\n一项动议被提出并表决通过：调整部分宣发任务的NT奖励额度，以匹配实际工作量。",
          },
          {
            date: "2026.06.17",
            phase: "2026.06.17 / 第五次会议",
            title: "进度同步与问题暴露",
            body: "6月17日，第五次会议。创作进度接近尾声，但新的不平衡开始显现：有的组画得快，有的组还在赶工；有人精力充沛，有人已经疲惫。\n\n这不是一个能通过单一动议解决的问题。会议采取了分项讨论的方式：进度问题（信息）→ 原因分析（理解）→ 各组提出的调整建议（观点）→ 达成一项临时决议：最后几天减少非创作类任务，集中精力完成作品。",
          },
          {
            date: "2026.06.18",
            phase: "2026.06.18 / 掀开屋顶大会",
            title: "关键转折：一个动议被否决后，调整再提",
            body: "6月18日上午，这场被称作「掀开屋顶大会」的会议，见证了议事规则最精彩的一幕。\n\nGloria提出一项动议：营期延长到6月22号之后，并在结束后多待几天，以较轻松的状态完成创作。\n\n动议进入表决程序。支持方陈述：作品尚未全部完成、赶工影响质量、前期紧迫感已下降。反对方表达担忧：延期可能导致活动与其他安排冲突、热度下降。\n\n表决结果：赞成0票，反对0票。动议被否决。\n\n但规则允许调整后重新提交。紧接着，FC作为系统角色介入，对动议进行了调整——明确了延期的具体天数、食宿费用和处理方式，并重新提出。\n\n这次，获默认一致同意。\n\n同一项想法，第一次被否决，调整方案后再提，通过。这就是规则的意义：不是让事情变难，而是让方案变得更周全。",
            image: "assets/images/story-photo.jpg",
          },
          {
            date: "2026.06.19",
            phase: "2026.06.19 / 掀开屋顶大会2",
            title: "延续决议：延期后的具体方案逐一敲定",
            body: "6月19日下午，延期动议通过后的第一次跟进会议。议题变为：延期期间的具体安排。\n\n多项议题并行推进：\n• 食宿费用：延期3天的住宿费如何计算？通过NT抵扣还是现金支付？最终形成方案——部分通过NT抵扣，超出部分按日折算。\n• 宣传任务：延期期间需要配合完成的宣传工作，以任务形式发布，完成后获得NT奖励。\n• 展览场地：合作社还是替代场地？等待投票结果确认。\n\n每一项都经历了事实澄清→观点表达→建议形成→表决的完整流程。到会议结束时，延期从一项「想法」变成了一套可执行的「方案」。",
          },
          {
            date: "2026.06.20",
            phase: "2026.06.20 / 第六次会议",
            title: "两项动议：乡村展与城市快闪展的双线并进",
            body: "6月20日下午，第六次会议。FC提出两项主动议：\n\n第一项动议：在22号于南塘合作社举办乡村展，并为此次展览安排庆功宴活动。\n第二项动议：在24号于城市举办快闪展（城市快闪展正式进入日程），同步安排庆功宴用餐环节。\n\n两项动议均获默认一致同意。\n\n至此，城市快闪展从「营期延长」的附带讨论中独立出来，成为一项独立的决议——不在原计划里，却通过完整的议事流程，被赋予了合法性。",
          },
          {
            date: "2026.06.21",
            phase: "2026.06.21 / 宣传框架会议",
            title: "从线下到线上：HTML网站的动议",
            body: "6月21日下午，艺术共创营系列宣传框架会议。FC提出一项主动议，在议事流程中完成了以下决议：\n\n• 为艺术共创营形成基础的HTML宣传框架与自适应窄屏呈现方案，覆盖第一期、第二期、第三期。\n• 以手机窄屏为主，电脑宽屏先不纳入。\n• 采用prototype迭代方式推进。\n• 第一期、第二期以呈现过往作品为主；第三期包含画廊和议事。\n• 首页标头介绍共创营的缘起、历程、当前状况和伙伴关系。\n\n这就是你现在看到的这个网站——它本身就是一场动议的产物。",
          },
          {
            date: "2026.06.23",
            phase: "2026.06.23 / 最终会议",
            title: "最终确认：费用、行前、第七次会议",
            body: "6月23日，三场会议密集进行：\n\n费用计算会议：对第三期的整体收支进行清理和确认，确保每项支出都有对应决议依据。\n\n城市展览行前会议：确认快闪展的参展作品清单、到场人员安排、布展流程和时间节点。\n\n第七次会议：对营期剩余阶段的各项工作进行最终表决和确认。\n\n三场会议完成时，第三期的所有关键决策都已走完「动议→辩论→表决→记录」的完整链路。剩下的，就是执行。",
          },
        ],
      },
    ],
  },
};
