export const navItems = [
  { key: "home", index: "01", title: "活动首页", subtitle: "活动总览与历期入口", href: "index.html" },
  { key: "phase-1", index: "02", title: "第一期", subtitle: "第一期详情页", href: "phase-1.html" },
  { key: "phase-2", index: "03", title: "第二期", subtitle: "第二期详情页", href: "phase-2.html" },
  { key: "phase-3", index: "04", title: "第三期", subtitle: "第三期主详情页", href: "phase-3.html" },
  { key: "story", index: "05", title: "共创故事", subtitle: "第三期时间线记录", href: "story.html" },
];

export const pages = {
  home: {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "首页导览",
    topbarIdentity: "活动首页",
    pageNumber: "01",
    banner: {
      kicker: "艺文共创 / 展览导览",
      handline: "共行山水之间",
      title: "南塘艺术\n共创营",
      intro: "以共创连接艺术、场地与人。这里不是一张普通活动海报，而是一页可以慢慢走读的艺术营导览。",
      status: "第三期进行中",
      noteTitle: "策展式浏览建议",
      noteText: "先认识活动，再浏览历期入口。每一期都像一张被展开的展签，保留自己的节奏与呼吸。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ABOUT THE CAMP",
        title: "一场持续发生的共创叙事",
        paragraphs: [
          "南塘艺术共创营以艺术实践为线索，把场地、创作者与公众观看连接在一起。它不是单次活动，而是一段被持续展开的现场。",
          "目前已完成三期内容，第三期仍在继续推进，第四期也已进入规划。你可以从历期入口中感受每一阶段的主题、作品与共同发生的故事。",
        ],
        note: "轻导航、展签式入口、层层展开的阅读节奏，将构成整个专题页的统一体验。",
      },
      {
        type: "archive",
        eyebrow: "ARCHIVE",
        title: "历期共创营",
        intro: "每一期都保留自己的主题气息。入口采用左右交错的展签式排布，让浏览更像在展场中移动。",
        after: {
          eyebrow: "NEXT",
          text: "第四期正在规划中，后续内容将陆续展开",
        },
        items: [
          {
            href: "phase-3.html",
            index: "03",
            tag: "第三期",
            line: "主题与图像在此交会",
            title: "正在发生的章节，仍然向前生长",
            body: "第三期是当前重点阶段，内容更完整，也更接近最终想被看见的共创面貌。",
            reverse: false,
          },
          {
            href: "phase-2.html",
            index: "02",
            tag: "第二期",
            line: "主题在回响",
            title: "在观看之间，延展彼此的回应",
            body: "第二期延续了共创的基础，用更开放的方式组织作品、记录与公众感知。",
            reverse: true,
          },
          {
            href: "phase-1.html",
            index: "01",
            tag: "第一期",
            line: "主题与图像在此交会",
            title: "以场地为纸，写下第一笔共创",
            body: "从第一次集结开始，共创营尝试让艺术介入空间，以作品和讨论打开现场的边界。",
            reverse: false,
          },
        ],
      },
      {
        type: "credits",
        eyebrow: "CREDITS",
        title: "工作人员",
        people: [
          { name: "待补充", role: "策展统筹" },
          { name: "待补充", role: "视觉设计" },
          { name: "待补充", role: "内容整理" },
          { name: "待补充", role: "待定角色" },
        ],
      },
    ],
  },
  "phase-1": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第一期 · 南塘",
    pageNumber: "02",
    banner: {
      kicker: "ISSUE 01 / FIELD NOTE",
      handline: "把相遇写进场地",
      title: "现场回声",
      intro: "第一期从一次集结开始。人与空间、图像与讨论在同一现场并置，慢慢生成最初的观看关系。",
      status: "已完成首期现场",
      noteTitle: "从场地出发",
      noteText: "先以简短线索建立主题，再用图像与作品说明展开阅读。详情页的节奏继续延续首页的展签式编排。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY NOTE",
        title: "本期活动介绍",
        paragraphs: [
          "第一期更像一次起笔。它尝试让艺术实践进入场地，让创作者在共同观看中找到彼此的回应方式。",
          "这里的文案、图像与作品信息都可以继续补充，但整体阅读路径已经先被搭好：背景、主题、说明，再进入作品。",
        ],
        note: "建议后续补入：活动时间、阶段主题、现场关键词或策划说明。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "保持左右交错的观看节奏。每组作品由图像区、窄栏题签和下方详细说明组成，便于后续继续补图补文。",
        items: [
          {
            reverse: false,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: true,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: false,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
        ],
      },
    ],
  },
  "phase-2": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第二期 · 南塘人物志",
    pageNumber: "03",
    banner: {
      kicker: "ISSUE 02 / RESPONSE NOTE",
      handline: "让回响慢慢成形",
      title: "现场回声",
      intro: "第二期延续了共创的基础。它更关注观看之间的回应，让记录、讨论与作品彼此牵引。",
      status: "第二期阶段整理",
      noteTitle: "沿着回应推进",
      noteText: "第二期的内容更适合通过对照阅读展开：一侧保留图像，一侧建立标题和短句，再往下补足细节。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY NOTE",
        title: "本期活动介绍",
        paragraphs: [
          "第二期不再只是起步，而是在已有基础上慢慢扩展出更明确的观看关系与共创方法。",
          "页面中的图像和文案仍可继续替换，但信息结构已经为后续补充预留了稳定位置。",
        ],
        note: "建议后续补入：阶段主题、参与方式、阶段成果与现场记录。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "第二期作品区延续图右文左、图左文右的交替结构，让阅读像在不同展签之间切换视角。",
        items: [
          {
            reverse: true,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: false,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: true,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
        ],
      },
    ],
  },
  "phase-3": {
    width: 430,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "现场回声",
    topbarIdentity: "第三期 · 寻找",
    pageNumber: "04",
    banner: {
      kicker: "ISSUE 03 / ONGOING FIELD",
      handline: "让故事继续生长",
      title: "现场回声",
      intro: "第三期是当前最完整、也仍在继续推进的一期。它既要说明活动本身，也要承接作品与共创人的阅读入口。",
      status: "第三期持续进行中",
      noteTitle: "第三期作为重点期数",
      noteText: "页面需要承担更多叙事说明，因此在作品区之外，再向下补充共创人的信息段落。",
    },
    sections: [
      {
        type: "text-card",
        eyebrow: "ACTIVITY DETAIL",
        title: "本期活动详情",
        paragraphs: [
          "这一期可以补充更完整的主题、背景、当前阶段与整体活动说明，形成第三期作为重点内容的主叙事。",
          "相比前两期，这里适合放更具体的阶段信息，例如当前进展、公开展示方式或正在推进的工作内容。",
        ],
        note: "建议后续补入：第三期主题、阶段关键词、共创方式、进行状态与后续计划。",
      },
      {
        type: "works",
        eyebrow: "WORKS",
        title: "作品展示",
        intro: "第三期作品区可比前两期更完整。每组作品下方都保留较长说明区，便于补充策展说明、创作过程与观看线索。",
        items: [
          {
            reverse: false,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: true,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
          {
            reverse: false,
            meta: "共创人名称",
            sideTitle: "作品名称",
            sideLine: "主题短介绍",
            body: "这里填写作品的详细介绍。可补充创作背景、材料方式、观看线索或现场反馈。",
          },
        ],
      },
      {
        type: "cocreators",
        eyebrow: "CO-CREATORS",
        title: "共创人",
        intro: "如果人物信息还未最终确定，可以先保留名单占位。当前先用两组错落的人物信息块延续整页节奏。",
        items: [
          {
            reverse: false,
            label: "CO-CREATOR 01",
            name: "姓名待补充",
            role: "身份 / 分工待补充",
            bio: "这里预留人物简介、参与方式或在第三期中的角色说明。",
          },
          {
            reverse: true,
            label: "CO-CREATOR 02",
            name: "姓名待补充",
            role: "身份 / 分工待补充",
            bio: "第二组与第一组形成轻微左右错位，后续可以继续向下追加更多人物条目。",
          },
        ],
      },
    ],
  },
  story: {
    width: 488,
    navLabelEn: "NANTANG ART CAMP",
    navLabelZh: "共创纪事",
    topbarIdentity: "第三期 · 共创纪事",
    pageNumber: "05",
    banner: {
      kicker: "CO-CREATION STORY",
      handline: "把过程留给时间",
      title: "共创纪事",
      intro: "这一页专门记录第三期共创从筹备到展开的过程纪事。阅读会按照阶段顺序向下展开，让每一段发生、讨论与回响都能被清楚看见。",
      status: "第三期过程纪事",
      noteTitle: "按阶段阅读过程",
      noteText: "每一则纪事都以时间、阶段与正文展开，重点保留讨论脉络、现场变化与共创推进，而不是用大幅配图打断阅读。",
    },
    sections: [
      {
        type: "timeline",
        eyebrow: "CHRONICLE",
        title: "第三期共创纪事",
        intro: "页面按阶段整理第三期的共创过程，沿着一条向下延展的时间轴阅读，让每一次筹备、对话、展开与回响都能被顺着看清。",
        items: [
          {
            date: "2026.06.06",
            phase: "2026.06.06 / 前期筹备",
            title: "从想法汇集到线索梳理",
            body: "这一阶段主要记录第三期如何被酝酿出来：从议题的提出、方向的讨论，到人物与场地线索的逐步聚拢，项目的轮廓开始被看见。文字应当把筹备中的判断、取舍与最初的期待保留下来，让读者理解后续行动并不是突然发生，而是从前期的多轮沟通中慢慢长出来的。",
          },
          {
            date: "2026.06.12",
            phase: "2026.06.12 / 走访对话",
            title: "在交流中确认共创的真实入口",
            body: "当走访、讨论和现场对话逐渐展开，项目开始从概念走向具体。这里适合记录参与者如何回应议题、哪些片段触发了新的判断、又有哪些问题在交流中被重新定义。相比概括性的活动介绍，这一部分更像工作笔记，要把语气、情境和关键转折写得足够清楚。",
          },
          {
            date: "2026.06.18",
            phase: "2026.06.18 / 共创展开",
            title: "把讨论真正转化为共同发生的现场",
            body: "进入共创展开阶段后，重点不再是说明项目要做什么，而是记录它如何被一起完成。可以写下现场分工、参与方式、阶段成果，以及某些被反复提及的细节如何推动了内容继续生长。若有少量关键影像，也只作为辅助说明存在，帮助读者感知现场气氛，而不抢走文字本身的叙事位置。",
            image: true,
          },
          {
            date: "2026.06.26",
            phase: "2026.06.26 / 呈现回响",
            title: "让阶段成果继续留下可追溯的回声",
            body: "这一部分适合承接阶段性的呈现、整理与回顾：哪些成果被留下、哪些反馈值得继续追踪、哪些问题又把下一轮行动重新打开。这样收束页面，不只是给第三期一个结尾，也是在告诉读者，共创并不是一次性事件，而是一条仍在继续生长的过程线。",
          },
        ],
      },
    ],
  },
};
